### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by rogueops** [pandu1990/Secure-Image-Encryption-Algorithm#1]
I have it loaded in eclipse and i run it and it says:

Usage: [enc filename|dec filename keyfile]

How do i input a file? I know java a little and have used this IDE, but not sure how to make your program work on an image i have encrypted.

Thanks in advance!

**Comment by DroneGj** [comment]
Usage: [enc filename|dec filename keyfile] is describing how to use this.

I am demonstrating how to use in Intellij. You need to add these arguments as runtime describing what you want to do. At intellij you can add arguments at menu run>edit configuration>program arguments. You can add them on your terminal directly while running.

**For Encryption:** 
enc followed by full path to the image you want to encrypt. 
Example: enc C:\Secure-Image-Encryption-Algorithm-master\images\eiffel-tower.jpg

_It will create an encrypted .png and a .key file for that image in the source image folder itself._

**For Decryption:**
dec followed by full path to the encrypted image followed by the key file for that image.
Example: dec C:\Secure-Image-Encryption-Algorithm-master\images\eiffel-tower.jpgenc.png C:\Secure-Image-Encryption-Algorithm-master\images\eiffel-tower.jpg.key

_It will create a decrypted .png as well as source format of file it's encrypted from on the source folder itself._

![Screenshot](https://user-images.githubusercontent.com/52096917/113983691-0902cb00-986c-11eb-8eed-d5f48d74b3fd.png)

**Comment by gunjan418** [comment]
Usage: [enc filename|dec filename keyfile] is describing how to use this.

I am demonstrating how to use in Intellij. You need to add these arguments at runtime describing what you want to do. At intellij you can add arguments at menu run>edit configuration>program arguments. You can also add them directly on your terminal while running.

**For Encryption:**
enc followed by full path to the image you want to encrypt.
Example: enc C:\Secure-Image-Encryption-Algorithm-master\images\eiffel-tower.jpg

_It will create an encrypted .png and a .key file for that image in the source image folder itself._

**For Decryption:**
dec followed by full path to the encrypted image followed by the key file for that image.
Example: dec C:\Secure-Image-Encryption-Algorithm-master\images\eiffel-tower.jpgenc.png C:\Secure-Image-Encryption-Algorithm-master\images\eiffel-tower.jpg.key

_It will create a decrypted .png as well as one same format of the file it's encrypted from in the source folder itself._
![Screenshot](https://user-images.githubusercontent.com/52096917/113984134-95ad8900-986c-11eb-9ceb-c37b67d6ef9c.png)

**Comment by pk4m** [comment]
In eclipse also it’s very similar. You just have to go to Run > Run Configurations > under Java Application create a new launch configuration and specify the arguments under Program Arguments.
